apiVersion: v1
kind: Service
metadata:
  name: service-portfolio
  labels:
    app: service-portfolio
spec:
  selector:
    app: service-portfolio
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
