apiVersion: v1
kind: Service
metadata:
  name: dns-resolver
  labels:
    app: dns-resolver
spec:
  selector:
    app: dns-resolver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
